# demo notebook

In [5]:
1 + 1

2

In [6]:
{ i:i * i for i in range(10)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

This demonstrates _dict comprehension_. It creates a dict with keys of $i = 0\dots10$ pointing to the corrresponding *squares*

In [12]:
import numpy as np

In [13]:
c = np.random.normal(size=(4,3))
print(c)

[[ 1.2857697   0.52113613 -0.75623288]
 [ 1.18578897  2.1016428  -0.35880136]
 [ 0.06179434  0.58010947  0.08141587]
 [-1.22568691  1.21328513 -1.75169178]]


In [14]:
c[:2]

array([[ 1.2857697 ,  0.52113613, -0.75623288],
       [ 1.18578897,  2.1016428 , -0.35880136]])

In [15]:
c[:2, 1:]

array([[ 0.52113613, -0.75623288],
       [ 2.1016428 , -0.35880136]])

In [16]:
c[::2, ::-1]

array([[-0.75623288,  0.52113613,  1.2857697 ],
       [ 0.08141587,  0.58010947,  0.06179434]])

In [21]:
d = 2 * (1 + np.arange(20))
d.reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [22]:
import pandas as pd

In [26]:
pd.Series([12.95, 19.50, 99.95, 5.00], index = ['blue', 'maroon', 'azure', 'khaki'])

blue      12.95
maroon    19.50
azure     99.95
khaki      5.00
dtype: float64

In [27]:
pd.Series([178000, 54000000, 68000, 730000], index = ['Seattle', 'New York City', 'Portland', 'Los Angeles'])

Seattle            178000
New York City    54000000
Portland            68000
Los Angeles        730000
dtype: int64

In [29]:
pd.DataFrame({'a':[1,2,3], "'b":[4,5,6], 'c':'a'}, index=['Bangkok', 'Shanghai', 'Cairo'])

a  'b  c
Bangkok   1   4  a
Shanghai  2   5  a
Cairo     3   6  a

In [30]:
pd.DataFrame({'Population':[7000000, 5000035, 78914921], 'Capital':['Washington DC', 'Cairo', 'New Delhi']}, index=['USA', 'Egypt', 'India'])

Population        Capital
USA       7000000  Washington DC
Egypt     5000035          Cairo
India    78914921      New Delhi

In [32]:
titanic = pd.read_csv('./titanic.csv.bz2')

In [33]:
titanic.shape

(1309, 14)

In [34]:
import os

In [35]:
os.getcwd()

'/Users/simrankota/Desktop/UW/Senior Year 2019-20/INFO 370'

In [36]:
titanic.head(5)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [37]:
titanic.tail(5)

pclass  survived                       name     sex   age  sibsp  parch  \
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [38]:
titanic.sample(5)

pclass  survived                                      name     sex  \
1152       3         0                   Robins, Mr. Alexander A    male   
725        3         1                      Connolly, Miss. Kate  female   
659        3         1            Baclini, Miss. Marie Catherine  female   
479        2         1  Laroche, Miss. Simonne Marie Anne Andree  female   
227        1         1         Pears, Mrs. Thomas (Edith Wearne)  female   

       age  sibsp  parch         ticket     fare cabin embarked boat   body  \
1152  50.0      1      0      A/5. 3337  14.5000   NaN        S  NaN  119.0   
725   22.0      0      0         370373   7.7500   NaN        Q   13    NaN   
659    5.0      2      1           2666  19.2583   NaN        C    C    NaN   
479    3.0      1      2  SC/Paris 2123  41.5792   NaN        C   14    NaN   
227   22.0      1      0         113776  66.6000    C2        S    8    NaN   

               home.dest  
1152                 NaN  
725              Ireland  
659   Syria New York, NY  
479        Paris / Haiti  
227   Isleworth, England

In [39]:
titanic.iloc[0]

pclass                                   1
survived                                 1
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                     29
sibsp                                    0
parch                                    0
ticket                               24160
fare                               211.338
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [40]:
titanic.iloc[[0]]

pclass  survived                           name     sex   age  sibsp  \
0       1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   

   parch ticket      fare cabin embarked boat  body     home.dest  
0      0  24160  211.3375    B5        S    2   NaN  St Louis, MO

In [41]:
titanic.iloc[[0,1,11,111,1111]]

pclass  survived                                               name  \
0          1         1                      Allen, Miss. Elisabeth Walton   
1          1         1                     Allison, Master. Hudson Trevor   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
111        1         1                     Fortune, Miss. Alice Elizabeth   
1111       3         0                     Peacock, Master. Alfred Edward   

         sex      age  sibsp  parch              ticket      fare  \
0     female  29.0000      0      0               24160  211.3375   
1       male   0.9167      1      2              113781  151.5500   
11    female  18.0000      1      0            PC 17757  227.5250   
111   female  24.0000      3      2               19950  263.0000   
1111    male   0.7500      1      1  SOTON/O.Q. 3101315   13.7750   

            cabin embarked boat  body                        home.dest  
0              B5        S    2   NaN                     St Louis, MO  
1         C22 C26        S   11   NaN  Montreal, PQ / Chesterville, ON  
11        C62 C64        C    4   NaN                     New York, NY  
111   C23 C25 C27        S   10   NaN                     Winnipeg, MB  
1111          NaN        S  NaN   NaN                              NaN

In [43]:
titanic.iloc[[0,1,11,111,1111], 2]

0                           Allen, Miss. Elisabeth Walton
1                          Allison, Master. Hudson Trevor
11      Astor, Mrs. John Jacob (Madeleine Talmadge Force)
111                        Fortune, Miss. Alice Elizabeth
1111                       Peacock, Master. Alfred Edward
Name: name, dtype: object

In [44]:
titanic.iloc[[0,1,11,111,1111], [1,2]]

survived                                               name
0            1                      Allen, Miss. Elisabeth Walton
1            1                     Allison, Master. Hudson Trevor
11           1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)
111          1                     Fortune, Miss. Alice Elizabeth
1111         0                     Peacock, Master. Alfred Edward

In [45]:
titanic.loc[[0, 1, 11, 111, 1111], ['survived', 'name']]

survived                                               name
0            1                      Allen, Miss. Elisabeth Walton
1            1                     Allison, Master. Hudson Trevor
11           1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)
111          1                     Fortune, Miss. Alice Elizabeth
1111         0                     Peacock, Master. Alfred Edward

In [46]:
titanic[['survived', 'name']]

survived                                             name
0            1                    Allen, Miss. Elisabeth Walton
1            1                   Allison, Master. Hudson Trevor
2            0                     Allison, Miss. Helen Loraine
3            0             Allison, Mr. Hudson Joshua Creighton
4            0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...        ...                                              ...
1304         0                             Zabour, Miss. Hileni
1305         0                            Zabour, Miss. Thamine
1306         0                        Zakarian, Mr. Mapriededer
1307         0                              Zakarian, Mr. Ortin
1308         0                               Zimmerman, Mr. Leo

[1309 rows x 2 columns]

In [47]:
titanic['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [48]:
titanic.name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [52]:
titanic['died'] = 1 - titanic.survived

In [58]:
theluckyones = titanic[titanic.survived == 1].copy()

In [59]:
theluckyones.shape

(500, 15)

In [60]:
theluckyones

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
5          1         1                              Anderson, Mr. Harry   
6          1         1                Andrews, Miss. Kornelia Theodosia   
8          1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...      ...       ...                                              ...   
1261       3         1                           Turkula, Mrs. (Hedwig)   
1277       3         1                             Vartanian, Mr. David   
1286       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
1290       3         1                 Wilkes, Mrs. James (Ellen Needs)   
1300       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   

         sex      age  sibsp  parch  ticket      fare    cabin embarked  \
0     female  29.0000      0      0   24160  211.3375       B5        S   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   
5       male  48.0000      0      0   19952   26.5500      E12        S   
6     female  63.0000      1      0   13502   77.9583       D7        S   
8     female  53.0000      2      0   11769   51.4792     C101        S   
...      ...      ...    ...    ...     ...       ...      ...      ...   
1261  female  63.0000      0      0    4134    9.5875      NaN        S   
1277    male  22.0000      0      0    2658    7.2250      NaN        C   
1286  female  38.0000      0      0    2688    7.2292      NaN        C   
1290  female  47.0000      1      0  363272    7.0000      NaN        S   
1300  female  15.0000      1      0    2659   14.4542      NaN        C   

       boat  body                        home.dest  died  
0         2   NaN                     St Louis, MO     0  
1        11   NaN  Montreal, PQ / Chesterville, ON     0  
5         3   NaN                     New York, NY     0  
6        10   NaN                       Hudson, NY     0  
8         D   NaN              Bayside, Queens, NY     0  
...     ...   ...                              ...   ...  
1261     15   NaN                              NaN     0  
1277  13 15   NaN                              NaN     0  
1286      C   NaN                              NaN     0  
1290    NaN   NaN                              NaN     0  
1300    NaN   NaN                              NaN     0  

[500 rows x 15 columns]

In [61]:
theluckyones['x'] = np.random.randint(1, 7, size = 500)

In [62]:
theluckyones

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
5          1         1                              Anderson, Mr. Harry   
6          1         1                Andrews, Miss. Kornelia Theodosia   
8          1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...      ...       ...                                              ...   
1261       3         1                           Turkula, Mrs. (Hedwig)   
1277       3         1                             Vartanian, Mr. David   
1286       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
1290       3         1                 Wilkes, Mrs. James (Ellen Needs)   
1300       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   

         sex      age  sibsp  parch  ticket      fare    cabin embarked  \
0     female  29.0000      0      0   24160  211.3375       B5        S   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   
5       male  48.0000      0      0   19952   26.5500      E12        S   
6     female  63.0000      1      0   13502   77.9583       D7        S   
8     female  53.0000      2      0   11769   51.4792     C101        S   
...      ...      ...    ...    ...     ...       ...      ...      ...   
1261  female  63.0000      0      0    4134    9.5875      NaN        S   
1277    male  22.0000      0      0    2658    7.2250      NaN        C   
1286  female  38.0000      0      0    2688    7.2292      NaN        C   
1290  female  47.0000      1      0  363272    7.0000      NaN        S   
1300  female  15.0000      1      0    2659   14.4542      NaN        C   

       boat  body                        home.dest  died  x  
0         2   NaN                     St Louis, MO     0  3  
1        11   NaN  Montreal, PQ / Chesterville, ON     0  4  
5         3   NaN                     New York, NY     0  2  
6        10   NaN                       Hudson, NY     0  3  
8         D   NaN              Bayside, Queens, NY     0  5  
...     ...   ...                              ...   ... ..  
1261     15   NaN                              NaN     0  6  
1277  13 15   NaN                              NaN     0  1  
1286      C   NaN                              NaN     0  6  
1290    NaN   NaN                              NaN     0  5  
1300    NaN   NaN                              NaN     0  1  

[500 rows x 16 columns]